5 individual article
sohailshams/nc-news pull request #3
Opened 2023-05-31 10:54 UTC by sohailshams

2023-05-31 11:07 UTC, johnhutcheon commented on src/api/api.js
> +export function ArtilceDetailAndComments(articleId, comment = "") {
You've combined two tickets into one here. Can you please separate this, so we have one function just getting the individual articles, and one just getting the comments?

2023-05-31 11:09 UTC, johnhutcheon requested changes
Hi Sohail. Please ensure that you're only submitting code for each individual ticket. I can see that you've combined tickets 5 and 6 here, and whilst the code works, we should only be seeing the code to take us to an individual article 👍 
Could you please separate the api calls so that there's a function to get the individual articles,  then resubmit please? You'll then need to do a separate request for the comments, which we'll look at separately.

2023-05-31 11:11 UTC, sohailshams commented
Hi John, I am sorry I did not reaize I have combined two tickets. I will separate them and submit PR again.

2023-06-01 10:19 UTC, johnhutcheon approved these changes

2023-06-01 10:25 UTC, merged